context.modules = [
  { name = libpipewire-module-filter-chain
    
    args = {
      node.description = "Speakers + Loudness"
      media.name = "Speakers + Loudness"
      filter.graph = {
        nodes = [
          { type = ladspa
            plugin = sc4m_1916
            label = sc4m
            name = comp
            control = {
              "RMS/peak" = 0.0
              "Attack time (ms)" = 3.0
              "Release time (ms)" = 150.0
              "Threshold level (dB)" = -20.0
              "Ratio (1:n)" = 4.0
              "Knee radius (dB)" = 8.0
              "Makeup gain (dB)" = 12.0
            }
          }
        ]
      }
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {
        node.name = "loudness_sink"
        media.class = Audio/Sink
      }
      playback.props = {
        node.name = "loudness_sink_out"
        node.passive = true
        target.object = "alsa_output.pci-0000_00_1b.0.analog-stereo"
      }
    }
  }
]
